chore: address pr feedback
- parameterize `provisioningMaxConsecutiveFailures` and `provisioningShutdownAllowanceSeconds`
- ensure background sleep is signalled in trap handler
- update `userguide.rst`

diff --git a/python/lsst/ctrl/bps/htcondor/etc/htcondor_defaults.yaml b/python/lsst/ctrl/bps/htcondor/etc/htcondor_defaults.yaml
--- a/python/lsst/ctrl/bps/htcondor/etc/htcondor_defaults.yaml
+++ b/python/lsst/ctrl/bps/htcondor/etc/htcondor_defaults.yaml
@@ -10,6 +10,8 @@ provisioning:
   provisioningNodeCount: 10
   provisioningMaxIdleTime: 900
   provisioningCheckInterval: 600
+  provisioningMaxConsecutiveFailures: 10
+  provisioningShutdownAllowanceSeconds: 20
   provisioningQueue: "milano"
   provisioningAccountingUser: "rubin:developers"
   provisioningExtraOptions: ""
@@ -20,38 +22,40 @@ provisioning:
 
     allocating=1
     failures=0
-    max_failures=10
+    max_failures='{provisioningMaxConsecutiveFailures}'
 
     allocate=("${CTRL_EXECUTE_DIR}/bin/allocateNodes.py" \
-          --account '{provisioningAccountingUser}' \
-          --auto \
-          --node-count '{provisioningNodeCount}' \
-          --maximum-wall-clock '{provisioningMaxWallTime}' \
-          --glidein-shutdown '{provisioningMaxIdleTime}' \
-          --queue '{provisioningQueue}' \
-          --nodeset '{nodeset}' \
-          {provisioningExtraOptions} \
-          '{provisioningPlatform}')
+      --account '{provisioningAccountingUser}' \
+      --auto \
+      --node-count '{provisioningNodeCount}' \
+      --maximum-wall-clock '{provisioningMaxWallTime}' \
+      --glidein-shutdown '{provisioningMaxIdleTime}' \
+      --queue '{provisioningQueue}' \
+      --nodeset '{nodeset}' \
+      {provisioningExtraOptions} \
+      '{provisioningPlatform}')
 
-    trap "allocating=0" SIGTERM
+    trap 'allocating=0; test -n "$bgpid" && kill -SIGTERM "$bgpid";' SIGTERM
 
     echo "$(date -u): starting provisioningJob"
     while (( allocating )); do
-        if "${allocate[@]}"; then
-          failures=0
-        else
-          echo "$(date -u): allocatedNodes failed" >&2
-          failures=$((failures + 1))
-        fi
-        if [[ $failures -ge $max_failures ]]; then
-          echo "$(date -u): Too many consecutive allocateNodes failures, exiting" >&2
-          exit 1
-        fi
-        sleep {provisioningCheckInterval} &
-        wait $! || :
+      if "${allocate[@]}"; then
+        failures=0
+      else
+        echo "$(date -u): allocatedNodes failed" >&2
+        failures=$((failures + 1))
+      fi
+      if [[ $failures -ge $max_failures ]]; then
+        echo "$(date -u): Too many consecutive allocateNodes failures, exiting" >&2
+        exit 1
+      fi
+      sleep {provisioningCheckInterval} &
+      bgpid=$!
+      wait $bgpid || :
     done
+
     echo "$(date -u): Shutting down provisioningJob..."
-    sleep 20
+    sleep '{provisioningShutdownAllowanceSeconds}'
     echo "$(date -u): Running FINAL provisioner"
     "${allocate[@]}"
     exit 0
